# DataRoot University DS100 Test #2
На проходження тесту виділяється 100 і одна хвилина.

## Python

### 1.  Реалізуйте функцію для видалення дублікатів зі списку списків:
У відповідь вивести результат роботи ф-ції для наступного списку:
```
[[10, 20], [40], [30, 56, 25], [10, 20], [33], [40], [42], [10, 42], [42]]
```


```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [5]:
def delete_duplicate(list_in_list):
    new_list = []
    for i in list_in_list:
        for n in i:
            new_list.append(n)
    new_list = set(new_list)
    return new_list

listing = [[10, 20], [40], [30, 56, 25], [10, 20], [33], [40], [42], [10, 42], [42]]
print (list(delete_duplicate(listing)))

[33, 40, 10, 42, 20, 56, 25, 30]


### 2.  Реалізуйте функцію str -> dict, таку, що ключем dict є символ строки, а значенням - його кількість в початковій str:
У відповідь вивести результат роботи ф-ції для наступної строки:
```"DataRoot University DS100 Test #2"```

```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [10]:
import re

def diction(string):
    first_symbol = string[0]
    return string.count(first_symbol)
    
    
print (diction("DataRoot University DS100 Test #2"))


2


### 3. Реалізуйте функцію, яка приймає два параметри: к-сть голів та к-сть ніг. За допомогою цієї функції вирішити наступну проблему: ми нарахували 35 голів та 94 ніг серед курей та кроликів на фермі. Скільки кроликів і скільки курей ми маємо?

```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 7хв
```

In [3]:
def count_animal(goals, legs):
    rabbit = (legs - (goals * 2)) / 2
    chicken = (legs - rabbit*4) / 2
    return rabbit, chicken

print (count_animal(35, 94))
    

(12.0, 23.0)


### 4. Реалізуйте клас під назвою Circle, побудований за радіусом та містить два способи, які обчислюють площу та периметр.

```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

In [42]:
class Circle:
    def square(self, radius):
        return 3.14 * radius**2
    
    def perimetr(self, radius):
        return 2 * 3.14 * radius**2
    
A = Circle()
print (A.square(2))

12.56


### 5.  Реалізуйте декоратор, який логує аргументи функцій та повернене значення кожного виклику. Необхідно виводити як позиційні(```*args```), так й іменовані аргументи(```**kwargs```):

Приклад застосування вашого декоратору в результаті:
```
>>> @log
... def func(*args):
...   return len(args)
>>> func(4, 4, 4)
you called func(4, 4, 4)
it returned 3
3
```

```
```
```
```
```
```
```
Максимальна оцінка: 4 бали
Рекомендований час: 15хв
```

NameError: name 'log' is not defined

## Libraries: numpy, scipy, pandas, matplotlib

### Numpy

### 6. Розв'яжіть систему рівнянь:


\begin{equation*}
 \begin{cases}
   x + y - z + 2 = 0
   \\
   3x - y + 2z - 9 = 0
   \\
   4x + 4y - 3z + 5 = 0
 \end{cases}
\end{equation*}

```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [8]:
import numpy as np

Matrix_A = np.array([[1, 1, -1],
           [3, -1, 2],
           [4, 4, -3]])
Matrix_B = np.array([-2, 9, -5])

print (np.linalg.solve(Matrix_A, Matrix_B))

[ 1.  0.  3.]


### 7. Дана матриця:
\begin{align}
A = \begin{bmatrix}
    17 & 24 & 1 & 8 & 15 \\
    23 & 5 & 7 & 14 & 16 \\
    4 & 6 & 13 & 20 & 22 \\
    10 & 12 & 19 & 21 & 3 \\
    11 & 18 & 25 & 2 & 9 \\
\end{bmatrix}
\end{align}
Знайти:

#### 7.1. Транспоновану: $A^{-1}$

```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [9]:
import numpy as np

matrix_A = np.array([[17, 24, 1, 8, 15],
             [23, 5, 7, 14, 16],
             [4, 6, 13, 20, 22],
             [10, 12, 19, 21, 3],
             [11, 18, 25, 2, 9]])

transponate_A = np.transpose(matrix_A)
print (transponate_A)

[[17 23  4 10 11]
 [24  5  6 12 18]
 [ 1  7 13 19 25]
 [ 8 14 20 21  2]
 [15 16 22  3  9]]


#### 7.2. Детермінант: $\det A$

```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [10]:
import numpy as np

matrix_A = np.array([[17, 24, 1, 8, 15],
             [23, 5, 7, 14, 16],
             [4, 6, 13, 20, 22],
             [10, 12, 19, 21, 3],
             [11, 18, 25, 2, 9]])

det_A = np.linalg.det(matrix_A)
print (det_A)

5070000.0


#### 7.3. Слід: $\DeclareMathOperator{\tr}{Tr}\tr A$
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [11]:
import numpy as np

matrix_A = np.array([[17, 24, 1, 8, 15],
             [23, 5, 7, 14, 16],
             [4, 6, 13, 20, 22],
             [10, 12, 19, 21, 3],
             [11, 18, 25, 2, 9]])

summ = 0
for i in range(5):
    summ += matrix_A[i][i]

print(summ)

65


#### 7.4. Доказати, що матриця А є магічним квадратом.
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

In [14]:
import numpy as np

matrix_A = np.array([[17, 24, 1, 8, 15],
             [23, 5, 7, 14, 16],
             [4, 6, 13, 20, 22],
             [10, 12, 19, 21, 3],
             [11, 18, 25, 2, 9]])

matrix_const_5 = 65
summ = 0

list_sum_0 = np.sum(matrix_A, axis=0)
list_sum_1 = np.sum(matrix_A, axis=1)

for i in range(5):
    summ += matrix_A[i][i]

for i in range(5):
    if list_sum_0[i] != matrix_const_5:
        print ("Its not magic square!")
        break
    elif list_sum_1[i] != matrix_const_5:
        print ("Its not magic square!")
        break
    elif summ != matrix_const_5:
        print ("Its not magic square!")
        break
    elif i == 4:
        print ("This is magic square!")


This is magic square!


### Pandas

### 8. Розглянемо наступний словник ```data``` та список ```labels```:

In [57]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

#### 8.1. Створіть ```DataFrame``` ```df``` з даних словника ```data``` з індексами зі списку ```labels```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [22]:
import pandas as pd


df = pd.DataFrame(data, index = labels)
df

age animal priority  visits
a  2.5    cat      yes       1
b  3.0    cat      yes       3
c  0.5  snake       no       2
d  NaN    dog      yes       3
e  5.0    dog       no       2
f  2.0    cat       no       3
g  4.5  snake       no       1
h  NaN    cat      yes       1
i  7.0    dog       no       2
j  3.0    dog       no       1

#### 8.2. Відобрзіть базову інформацію про цей ```DataFrame``` та його дані:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
age         8 non-null float64
animal      10 non-null object
priority    10 non-null object
visits      10 non-null int64
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


#### 8.3. Поверніть перші 3 рядки ```DataFrame``` ```df```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [23]:
df[:3]

age animal priority  visits
a  2.5    cat      yes       1
b  3.0    cat      yes       3
c  0.5  snake       no       2

#### 8.4. Виберіть стовпчики ```"animal"``` та ```"age"``` з ```DataFrame``` ```df```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [41]:
df[["animal","age"]]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog -1.0
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat -1.0
i    dog  7.0
j    dog  3.0

#### 8.5 Виберіть дані з рядків ```[3, 4, 8]``` та стовпчиків ```['animal', 'age']```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [30]:
df.loc[['a', 'c' , 'f'], ['animal', 'age']]

animal  age
a    cat  2.5
c  snake  0.5
f    cat  2.0

#### 8.6. Виберіть лише ті рядки, в яких к-сть візитів більша ніж 3:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [31]:
df[df.visits > 2]

age animal priority  visits
b  3.0    cat      yes       3
d  NaN    dog      yes       3
f  2.0    cat       no       3

#### 8.7. Виберіть рядки, де вік відсутній, тобто ```NaN```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [39]:
df.fillna(0)

age animal priority  visits
a  2.5    cat      yes       1
b  3.0    cat      yes       3
c  0.5  snake       no       2
d -1.0    dog      yes       3
e  5.0    dog       no       2
f  2.0    cat       no       3
g  4.5  snake       no       1
h -1.0    cat      yes       1
i  7.0    dog       no       2
j  3.0    dog       no       1

#### 8.8. Виберіть рядки з котами, вік яких менше ніж 3:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [40]:
df[[df.age < 3] and df.animal == 'cat']

age animal priority  visits
a  2.5    cat      yes       1
b  3.0    cat      yes       3
f  2.0    cat       no       3
h -1.0    cat      yes       1

#### 8.9. Підрахуйте середній вік для кожного з типів тварин:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 4хв
```

In [52]:
df.groupby('animal').mean()

age  visits
animal               
cat     1.625     2.0
dog     3.500     2.0
snake   2.500     1.5

#### 8.10. Відсортуйте ```df``` по-перше за віком в спадаючому порядку, по-друге за к-стю візитів в зростаючому порядку:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 4хв
```

In [55]:
df.sort_values('age', ascending = False)
df.sort_values('visits')

age animal priority  visits
a  2.5    cat      yes       1
g  4.5  snake       no       1
h -1.0    cat      yes       1
j  3.0    dog       no       1
c  0.5  snake       no       2
e  5.0    dog       no       2
i  7.0    dog       no       2
b  3.0    cat      yes       3
d -1.0    dog      yes       3
f  2.0    cat       no       3

#### 8.11. В ```'animal'``` ствобчику, змініть всіх ```'snake'``` на ```'python'```:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 4хв
```

In [79]:
df.animal.replace(to_replace=['snake'], value=['python'], inplace = True)
df

age  animal priority  visits
a  2.5     cat      yes       1
b  3.0     cat      yes       3
c  0.5  python       no       2
d -1.0     dog      yes       3
e  5.0     dog       no       2
f  2.0     cat       no       3
g  4.5  python       no       1
h -1.0     cat      yes       1
i  7.0     dog       no       2
j  3.0     dog       no       1

## Scipy & Matplotlib

### 9. За допомогою scipy згенерувати та за допомогою matplotlib побудувати вибірки, правильно підписавши осі та назвавши графік з обраними відповідними параметрами:

#### 9.1. Виібрку з нормально розподіленої випадкової величини:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.2. Вибірку з розподілу Бернулі:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.3. Вибірку з біноміального розподілу:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.4. Вибірку з розподілу Пуассона:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```